// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(UrbanBookDbContext))]
    [Migration("20260226164916_AddLandingPageCustomization")]
    partial class AddLandingPageCustomization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.DCalendario.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsScheduled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<int?>("StateProcessEventId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EventoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("IsScheduled");

                    b.HasIndex("NegocioId");

                    b.HasIndex("StateProcessEventId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DCalendario.StateProcessEvents", b =>
                {
                    b.Property<int>("StateProcessEventsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StateProcessEventsId"));

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StateProcessEventsId");

                    b.ToTable("StateProcessEvent", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingConfig", b =>
                {
                    b.Property<int>("LandingConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LandingConfigId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeroImageFileName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeroSubtitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsAppMessage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("LandingConfigId");

                    b.HasIndex("NegocioId");

                    b.ToTable("LandingConfigs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingGalleryItem", b =>
                {
                    b.Property<int>("LandingGalleryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LandingGalleryItemId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("LandingConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("LandingGalleryItemId");

                    b.HasIndex("LandingConfigId");

                    b.HasIndex("NegocioId");

                    b.ToTable("LandingGalleryItems", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingService", b =>
                {
                    b.Property<int>("LandingServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LandingServiceId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IconCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LandingConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("LandingServiceId");

                    b.HasIndex("LandingConfigId");

                    b.HasIndex("NegocioId");

                    b.ToTable("LandingServices", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DMessaging.SmtpConfig", b =>
                {
                    b.Property<int>("SmtpConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SmtpConfigId"));

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SmtpConfigId");

                    b.HasIndex("NegocioId");

                    b.ToTable("SmtpConfigs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DNegocio.Negocio", b =>
                {
                    b.Property<int>("NegocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NegocioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("NegocioId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DOtp.OtpVerification", b =>
                {
                    b.Property<int>("OtpVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OtpVerificationId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OtpVerificationId");

                    b.HasIndex("NegocioId");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("Domain.Entities.DServicio.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServicioId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ServicioId");

                    b.HasIndex("NegocioId");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.ExclusionHorario", b =>
                {
                    b.Property<int>("ExclusionHorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExclusionHorarioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("HorarioAtencionId")
                        .HasColumnType("integer");

                    b.HasKey("ExclusionHorarioId");

                    b.HasIndex("HorarioAtencionId");

                    b.ToTable("ExclusionHorario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.HorarioAtencion", b =>
                {
                    b.Property<int>("HorarioAtencionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorarioAtencionId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("HorarioAtencionId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UsuarioId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("HorarioAtencion", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.Perfil", b =>
                {
                    b.Property<int>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerfilId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PerfilId");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NegocioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Dcliente.Cliente", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("clienteId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("clienteId");

                    b.HasIndex("NegocioId");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Parametros.Parameter", b =>
                {
                    b.Property<int>("IdParameter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParameter"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreationUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifierUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("integer");

                    b.Property<string>("TypeParameter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdParameter");

                    b.HasIndex("NegocioId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Parametros.Value", b =>
                {
                    b.Property<int>("IdValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdValue"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdParameter")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdValue");

                    b.HasIndex("IdParameter");

                    b.ToTable("Values", (string)null);
                });

            modelBuilder.Entity("PerfilUsuario", b =>
                {
                    b.Property<int>("PerfilesPerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuariosUsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("PerfilesPerfilId", "UsuariosUsuarioId");

                    b.HasIndex("UsuariosUsuarioId");

                    b.ToTable("UsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DCalendario.Evento", b =>
                {
                    b.HasOne("Domain.Entities.Dcliente.Cliente", "Cliente")
                        .WithMany("Eventos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("Eventos")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DCalendario.StateProcessEvents", "StateProcessEvent")
                        .WithMany("Eventos")
                        .HasForeignKey("StateProcessEventId");

                    b.HasOne("Domain.Entities.DUsuario.Usuario", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");

                    b.Navigation("StateProcessEvent");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingConfig", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("LandingConfigs")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingGalleryItem", b =>
                {
                    b.HasOne("Domain.Entities.DLandingPage.LandingConfig", "LandingConfig")
                        .WithMany("LandingGalleryItems")
                        .HasForeignKey("LandingConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LandingConfig");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingService", b =>
                {
                    b.HasOne("Domain.Entities.DLandingPage.LandingConfig", "LandingConfig")
                        .WithMany("LandingServices")
                        .HasForeignKey("LandingConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LandingConfig");

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DMessaging.SmtpConfig", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("SmtpConfigs")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DOtp.OtpVerification", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DServicio.Servicio", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("Servicios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.ExclusionHorario", b =>
                {
                    b.HasOne("Domain.Entities.DUsuario.HorarioAtencion", "HorarioAtencion")
                        .WithMany("Exclusiones")
                        .HasForeignKey("HorarioAtencionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioAtencion");
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.HorarioAtencion", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DUsuario.Usuario", "Usuario")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.Usuario", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("Usuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.Dcliente.Cliente", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("Clientes")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.Parametros.Parameter", b =>
                {
                    b.HasOne("Domain.Entities.DNegocio.Negocio", "Negocio")
                        .WithMany("Parameters")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Domain.Entities.Parametros.Value", b =>
                {
                    b.HasOne("Domain.Entities.Parametros.Parameter", "Parameters")
                        .WithMany("Values")
                        .HasForeignKey("IdParameter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("PerfilUsuario", b =>
                {
                    b.HasOne("Domain.Entities.DUsuario.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilesPerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DUsuario.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.DCalendario.StateProcessEvents", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Domain.Entities.DLandingPage.LandingConfig", b =>
                {
                    b.Navigation("LandingGalleryItems");

                    b.Navigation("LandingServices");
                });

            modelBuilder.Entity("Domain.Entities.DNegocio.Negocio", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Eventos");

                    b.Navigation("HorariosAtencion");

                    b.Navigation("LandingConfigs");

                    b.Navigation("Parameters");

                    b.Navigation("Servicios");

                    b.Navigation("SmtpConfigs");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.HorarioAtencion", b =>
                {
                    b.Navigation("Exclusiones");
                });

            modelBuilder.Entity("Domain.Entities.DUsuario.Usuario", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("HorariosAtencion");
                });

            modelBuilder.Entity("Domain.Entities.Dcliente.Cliente", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Domain.Entities.Parametros.Parameter", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
